export default {
    colors: {
        main: '#ccc',
        mainBackground: '#080808',
        searchInput: '#fff',
        searchInputBorder: '#333',
        searchInputBorderOnFocus: '#ff8849',
        searchInputBackground: '#000',
        searchButton: '#000',
        searchButtonBackground: '#ff8849',
        searchButtonBackgroundOnHover: '#fdc175',
        searchResult: '#ccc',
        searchResultOnHover: '#000',
        searchResultBackground: '#000',
        searchResultBackgroundOnHover: '#ff8849',
        userHeaderBackground: '#151515',
        userPaginationButton: '#000',
        userPaginationButtonBackground: '#ff8849',
        userPaginationButtonBackgroundOnHover: '#fdc175',
        userRepositoryBorder: '#333',
        backButton: '#000',
        backButtonBackground: '#ff8849',
        backButtonBackgroundOnHover: '#fdc175',
        username: '#ccc',
        userRepositoriesCount: '#999',
        userRepositoryName: '#ccc',
        userRepositoriesDescription: '#999',
        pageCount: '#ccc',
        pageSpinner: '#ff8849',
        header: '#ccc',
        homeLinkOnHover: '#fdc175',
        changeThemeButtonOnHover: '#fdc175',
        headerBackground: '#333'
    }
};
