export default {
    colors: {
        main: '#333',
        mainBackground: '#f7f7f7',
        searchInput: '#000',
        searchInputBorder: '#ccc',
        searchInputBorderOnFocus: '#0077b6',
        searchInputBackground: '#fff',
        searchButton: '#fff',
        searchButtonBackground: '#0077b6',
        searchButtonBackgroundOnHover: '#023e8a',
        searchResult: '#333',
        searchResultOnHover: '#fff',
        searchResultBackground: '#fff',
        searchResultBackgroundOnHover: '#0077b6',
        userHeaderBackground: '#eaeaea',
        userPaginationButton: '#fff',
        userPaginationButtonBackground: '#0077b6',
        userPaginationButtonBackgroundOnHover: '#023e8a',
        userRepositoryBorder: '#ccc',
        backButton: '#fff',
        backButtonBackground: '#0077b6',
        backButtonBackgroundOnHover: '#023e8a',
        username: '#333',
        userRepositoriesCount: '#666',
        userRepositoryName: '#333',
        userRepositoriesDescription: '#666',
        pageCount: '#333',
        pageSpinner: '#0077b6',
        header: '#333',
        homeLinkOnHover: '#023e8a',
        changeThemeButtonOnHover: '#023e8a',
        headerBackground: '#ccc'
    }
};
